In [ ]:
import cv2
import numpy as np

In [2]:
img= cv2.imread("E:/user/Pictures/Saved Pictures/pragathi/BFBWOhuG0GB.jpg", 1)

In [3]:
img2= cv2.imread("E:/user/Pictures/Saved Pictures/vinnyopt.jpg", 0)

In [4]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ..., 
 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [5]:
print(img2)

[[224 217 218 ..., 213 215 224]
 [217 209 209 ..., 205 207 215]
 [219 210 209 ..., 206 207 216]
 ..., 
 [ 36  38  38 ...,  37  38  41]
 [ 37  35  37 ...,  32  34  38]
 [ 33  43  46 ...,  21  24  29]]


In [6]:
print(type(img))

<class 'numpy.ndarray'>


In [7]:
cv2.imshow("vinith", img)
cv2.waitKey(1000)
cv2.destroyAllWindows()

In [8]:
face_cascade = cv2.CascadeClassifier("C:/Users/user/Anaconda3/envs/opencv-env/Lib/site-packages/cv2/data/haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier("C:/Users/user/Anaconda3/envs/opencv-env/Lib/site-packages/cv2/data/haarcascade_eye.xml")

In [9]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [10]:
faces = face_cascade.detectMultiScale(gray, 1.3, 5)

In [11]:
for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_cascade.detectMultiScale(roi_gray)
    for(ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)

In [12]:
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()